apiVersion: v1
kind: Service
metadata:
  name: devops-demo-Service
  namespace:default
spec:
  selector:
    app: devops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


